In [1]:
from google.colab import drive
drive.mount('/content.drive')

Mounted at /content.drive

In [2]:
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv("/content.drive/MyDrive/data/BDP_PROJECT/2019/data2019.csv")

In [13]:
data.head()

,Unnamed: 0,Unnamed: 0.1,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,0,0.0,SPB-10632,2019-01-01 00:00:44,1421,신내역 4번출구,3,2019-01-01 00:03:53,1420,신내어울공원 앞,13,2,580.0
1,1,1.0,SPB-10957,2019-01-01 00:02:16,1408,먹골역 6번출구 앞,3,2019-01-01 00:07:07,1433,중화역 2번출구,4,4,1020.0
2,2,2.0,SPB-16067,2019-01-01 00:04:12,347,동대문역사문화공원역 9번출구 앞,17,2019-01-01 00:07:07,387,훈련원공원주차장 앞,1,2,550.0
3,3,3.0,SPB-17170,2019-01-01 00:03:09,615,용두동 래미안허브리츠아파트 앞,4,2019-01-01 00:07:27,612,시립동부병원 앞 사거리,14,3,700.0
4,4,4.0,SPB-14130,2019-01-01 00:01:44,1177,수명중?고교,7,2019-01-01 00:08:09,1152,마곡역교차로,1,5,1090.0

In [14]:
data.isnull().sum()

Unnamed: 0            0
Unnamed: 0.1    1048575
자전거번호                 0
대여일시                  0
대여소번호                 0
대여대여소명                0
대여거치대                 0
반납일시                  0
반납대여소번호               0
반납대여소명                0
반납거치대                 0
이용시간                  0
이용거리                  0
dtype: int64

In [15]:
data.sort_values('이용거리')

,Unnamed: 0,Unnamed: 0.1,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
328728,328728,328728.0,SPB-03904,2019-01-22 21:36:14,104,합정역 1번출구 앞,9,2019-01-22 21:41:21,101,(구)합정동 주민센터,3,4,0.0
554557,554557,68856.0,SPB-01264,2019-02-07 12:32:18,1218,방이역 4번출구,10,2019-02-07 12:44:23,1215,올림픽공원역 1번출구 앞,5,11,0.0
1583418,1583418,635745.0,SPB-04430,2019-03-24 12:51:35,3509,세종사이버대학교,10,2019-03-24 13:04:37,567,성수역 2번출구 앞,11,12,0.0
44074,44074,44074.0,SPB-13872,2019-01-04 10:41:08,557,도선동 주민센터 앞,2,2019-01-04 10:47:14,605,신설동역8번출구,5,5,0.0
2424017,591208,NaN,SPB-09506,2019.5.9 12:46,201,진미파라곤 앞,3,2019.5.9 12:51,201,진미파라곤 앞,3,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2678610,845801,NaN,SPB-15109,2019.5.12 20:12,802,한강진역 2번 출구 앞,8,2019.5.12 20:34,2262,한신16차아파트 119동 앞,9,21,255730.0
2507695,674886,NaN,SPB-15135,2019.5.10 16:30,513,뚝섬역 5번 출구 정류소 옆,7,2019.5.10 16:45,558,성동광진 교육지원청 앞,9,14,255790.0
2838480,1005671,NaN,SPB-14934,2019.5.14 22:43,152,마포구민체육센터 앞,30,2019.5.14 23:23,196,연희교차로 인근,7,39,255810.0
2710117,877308,NaN,SPB-15167,2019.5.13 8:56,1009,천호역4번출구(현대백화점),17,2019.5.13 9:03,1022,길동 사거리(초소앞),7,6,255890.0
2401797,568988,NaN,SPB-13890,2019.5.8 23:34,1449,상봉역 1번출구,11,2019.5.9 0:38,525,한양대병원사거리,8,63,255990.0

In [10]:
data['이용거리'].value_counts()

0.0         42584
910.0       11117
1100.0      10781
900.0       10743
980.0       10682
            ...
234160.0        1
86750.0         1
82790.0         1
203750.0        1
130480.0        1
Name: 이용거리, Length: 10273, dtype: int64

In [25]:
data[(data['이용시간']==0)&(data['이용거리']>100)].sort_values('이용거리')

,Unnamed: 0,Unnamed: 0.1,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
2516877,684068,NaN,SPB-10122,2019.5.10 17:48,334,종로3가역 2번출구 뒤,4,2019.5.10 18:30,364,창신역 1번출구 앞,1,0,110.0
1935484,102675,NaN,SPB-12802,2019.5.2 14:33,2279,교대역 5번출구뒤,6,2019.5.2 14:34,2239,교대역 6번출구,6,0,110.0
2634645,801836,NaN,SPB-19066,2019.5.12 10:20,1299,송파소방서 (방이119안전센터),1,2019.5.12 10:21,2609,보성중고등학교 후문 앞,8,0,110.0
2359467,526658,NaN,SPB-15072,2019.5.8 14:43,2110,조원동 미성아파트,5,2019.5.8 14:44,1955,디지털입구 교차로,7,0,120.0
1897686,64877,NaN,SPB-06430,2019.5.1 21:19,518,청계천 박물관 앞,17,2019.5.1 21:21,550,서울시설공단 앞,11,0,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2689955,857146,NaN,SPB-12310,2019.5.12 21:37,2259,잠원역 3번-4번 출구사이,8,2019.5.12 22:44,1231,잠실역 6번출구,6,0,11720.0
2383128,550319,NaN,SPB-07975,2019.5.8 18:09,1998,고척교 교차로,6,2019.5.8 19:36,248,초원아파트 앞,6,0,12060.0
2506793,673984,NaN,SPB-18151,2019.5.10 16:29,737,장수공원,1,2019.5.10 16:30,706,신정네거리역,1,0,29460.0
2046107,213298,NaN,SPB-20162,2019.5.3 20:36,154,마포구청역,12,2019.5.3 22:13,105,합정역 5번출구 앞,1,0,60240.0
2803919,971110,NaN,SPB-20131,2019.5.14 17:45,312,시청역 1번출구 뒤,7,2019.5.14 17:48,310,청계광장 옆,2,0,60950.0

In [16]:
new_data = data[(data['이용시간']>10)|(data["이용거리"]!=0)].sort_values('이용시간')
new_data.head()

,Unnamed: 0,Unnamed: 0.1,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
1852800,19991,NaN,SPB-14204,2019.5.1 12:48,591,건국대학교 (행정관),4,2019.5.1 12:50,592,건국대학교 학생회관,1,0,210.0
2857517,1024708,NaN,SPB-17654,2019.5.15 8:55,213,KT앞,14,2019.5.15 8:56,214,금융감독원 앞,14,0,180.0
2208030,375221,NaN,SPB-19813,2019.5.6 14:08,2102,봉림교 교통섬,1,2019.5.6 14:18,2183,동방1교,1,0,2350.0
2359467,526658,NaN,SPB-15072,2019.5.8 14:43,2110,조원동 미성아파트,5,2019.5.8 14:44,1955,디지털입구 교차로,7,0,120.0
2747273,914464,NaN,SPB-01140,2019.5.13 20:11,502,뚝섬유원지역 1번출구 앞,12,2019.5.13 20:12,588,뚝섬 유원지역,4,0,100.0